---
version: '2'
services:
  datastore:
    build: containers/datastore
    container_name: minio-sample-container
  mysql:
    image: mysql:5.6.35
    command: mysqld --character-set-server=utf8
    env_file:
    - ./docker-compose.env
    ports:
    - '3306:3306'
    volumes_from:
    - datastore
  minio:
    build:
      context: .
      dockerfile: Dockerfile-minio
    ports:
      - '9000:9000'
    command: [server, /minio]
    volumes_from:
    - datastore
    env_file:
    - ./docker-compose.env
  rails:
    build: .
    depends_on:
    - minio
    - mysql
    ports:
      - '3000:3000'
    env_file:
    - ./docker-compose.env
    environment:
      RAILS_ENV: docker
    volumes:
    - .:/usr/src/app
    volumes_from:
    - datastore
    links:
      - minio
      - mysql
